FROM nginx:latest
# Hapus konfigurasi default Nginx
RUN rm /etc/nginx/conf.d/default.conf
# Salin konfigurasi custom Anda
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
